import type { ProviderCatalogEntry, ProviderModel } from "@/types/providers";

const m = (model: ProviderModel): ProviderModel => model;

export const PROVIDER_CATALOG: ProviderCatalogEntry[] = [
  {
    id: "openai",
    displayName: "OpenAI",
    docsUrl: "https://platform.openai.com/docs/models",
    baseUrl: "https://api.openai.com/v1",
    logoPath: "/providers/openai.svg",
    keyPlaceholder: "sk-...",
    supportedSettings: ["temperature", "topP", "presencePenalty", "frequencyPenalty", "maxOutputTokens", "seed"],
    lastVerified: "2026-03-28",
    notes: "Model list aligned with OpenAI model docs. Verify live pricing before billing decisions.",
    models: [
      m({ modelId: "gpt-5", displayName: "GPT-5", category: "flagship", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: true, supportsFrequencyPenalty: true, supportsSeed: true, supportsReasoningEffort: true, defaultTemperature: 1, notes: "Primary frontier model." }),
      m({ modelId: "gpt-5-mini", displayName: "GPT-5 Mini", category: "balanced", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: true, supportsFrequencyPenalty: true, supportsSeed: true, supportsReasoningEffort: true, defaultTemperature: 1, notes: "Lower-cost balanced option." }),
      m({ modelId: "gpt-5-nano", displayName: "GPT-5 Nano", category: "nano", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Fast/cheap tier." }),
      m({ modelId: "gpt-4.1", displayName: "GPT-4.1", category: "flagship", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 1_000_000, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: true, supportsFrequencyPenalty: true, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 1, notes: "High-quality general model." }),
      m({ modelId: "gpt-4.1-mini", displayName: "GPT-4.1 Mini", category: "mini", inputPricePer1M: 0.4, outputPricePer1M: 1.6, currency: "USD", contextWindow: 1_000_000, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: true, supportsFrequencyPenalty: true, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Stable default for budget-sensitive tasks." }),
    ],
  },
  {
    id: "gemini",
    displayName: "Google Gemini",
    docsUrl: "https://ai.google.dev/gemini-api/docs/models",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    logoPath: "/providers/gemini.svg",
    keyPlaceholder: "AIza...",
    supportedSettings: ["temperature", "topP", "topK", "maxOutputTokens", "seed"],
    lastVerified: "2026-03-28",
    notes: "Gemini safety filters are configurable per harm category.",
    models: [
      m({ modelId: "gemini-2.5-pro", displayName: "Gemini 2.5 Pro", category: "flagship", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 1_000_000, supportsTemperature: true, supportsTopP: true, supportsTopK: true, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 1, notes: "High capability model." }),
      m({ modelId: "gemini-2.5-flash", displayName: "Gemini 2.5 Flash", category: "fast", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 1_000_000, supportsTemperature: true, supportsTopP: true, supportsTopK: true, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Fast default for production." }),
      m({ modelId: "gemini-2.5-flash-lite", displayName: "Gemini 2.5 Flash-Lite", category: "mini", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 1_000_000, supportsTemperature: true, supportsTopP: true, supportsTopK: true, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Cost-optimized flash tier." }),
      m({ modelId: "gemini-2.0-flash", displayName: "Gemini 2.0 Flash", category: "balanced", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: true, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Broad compatibility." }),
      m({ modelId: "gemini-2.0-flash-lite", displayName: "Gemini 2.0 Flash-Lite", category: "mini", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: true, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Low-cost text and multimodal tasks." }),
    ],
  },
  {
    id: "anthropic",
    displayName: "Anthropic",
    docsUrl: "https://docs.anthropic.com/en/docs/about-claude/models",
    baseUrl: "https://api.anthropic.com/v1",
    logoPath: "/providers/anthropic.svg",
    keyPlaceholder: "sk-ant-...",
    supportedSettings: ["temperature", "topP", "topK", "maxOutputTokens"],
    lastVerified: "2026-03-28",
    notes: "Claude commonly omits presence/frequency penalties.",
    models: [
      m({ modelId: "claude-opus-4.1", displayName: "Claude Opus 4.1", category: "flagship", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 200_000, supportsTemperature: true, supportsTopP: true, supportsTopK: true, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: false, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Most capable Claude tier." }),
      m({ modelId: "claude-opus-4", displayName: "Claude Opus 4", category: "flagship", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 200_000, supportsTemperature: true, supportsTopP: true, supportsTopK: true, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: false, supportsReasoningEffort: false, defaultTemperature: 1, notes: "High-quality reasoning and coding." }),
      m({ modelId: "claude-sonnet-4", displayName: "Claude Sonnet 4", category: "balanced", inputPricePer1M: 3, outputPricePer1M: 15, currency: "USD", contextWindow: 200_000, supportsTemperature: true, supportsTopP: true, supportsTopK: true, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: false, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Balanced flagship option." }),
      m({ modelId: "claude-3-7-sonnet", displayName: "Claude 3.7 Sonnet", category: "reasoning", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 200_000, supportsTemperature: true, supportsTopP: true, supportsTopK: true, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: false, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Reasoning-focused generation." }),
      m({ modelId: "claude-3-5-haiku", displayName: "Claude 3.5 Haiku", category: "fast", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 200_000, supportsTemperature: true, supportsTopP: true, supportsTopK: true, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: false, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Fast lower-cost Claude." }),
    ],
  },
  {
    id: "xai",
    displayName: "xAI",
    docsUrl: "https://docs.x.ai/docs/models",
    baseUrl: "https://api.x.ai/v1",
    logoPath: "/providers/xai.svg",
    keyPlaceholder: "xai-...",
    supportedSettings: ["temperature", "topP", "maxOutputTokens", "seed"],
    lastVerified: "2026-03-28",
    notes: "xAI exposes OpenAI-compatible endpoints; support can vary by model.",
    models: [
      m({ modelId: "grok-4", displayName: "Grok 4", category: "flagship", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Top-tier Grok model." }),
      m({ modelId: "grok-4-fast", displayName: "Grok 4 Fast", category: "fast", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Lower-latency Grok tier." }),
      m({ modelId: "grok-3", displayName: "Grok 3", category: "balanced", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Prior-generation mainstream model." }),
      m({ modelId: "grok-3-mini", displayName: "Grok 3 Mini", category: "mini", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Smaller inexpensive model." }),
      m({ modelId: "grok-2", displayName: "Grok 2", category: "balanced", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Legacy compatibility." }),
    ],
  },
  {
    id: "deepseek",
    displayName: "DeepSeek",
    docsUrl: "https://api-docs.deepseek.com/quick_start/pricing",
    baseUrl: "https://api.deepseek.com/v1",
    logoPath: "/providers/deepseek.svg",
    keyPlaceholder: "sk-...",
    supportedSettings: ["temperature", "topP", "frequencyPenalty", "presencePenalty", "maxOutputTokens"],
    lastVerified: "2026-03-28",
    notes: "DeepSeek pricing includes context cache nuances.",
    models: [
      m({ modelId: "deepseek-v3", displayName: "DeepSeek V3", category: "flagship", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 128_000, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: true, supportsFrequencyPenalty: true, supportsSeed: false, supportsReasoningEffort: false, defaultTemperature: 1, notes: "General flagship model." }),
      m({ modelId: "deepseek-r1", displayName: "DeepSeek R1", category: "reasoning", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 128_000, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: false, supportsReasoningEffort: true, defaultTemperature: 0.6, notes: "Reasoning-specialized model." }),
      m({ modelId: "deepseek-chat", displayName: "DeepSeek Chat", category: "balanced", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 128_000, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: true, supportsFrequencyPenalty: true, supportsSeed: false, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Stable chat target." }),
      m({ modelId: "deepseek-reasoner", displayName: "DeepSeek Reasoner", category: "reasoning", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 128_000, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: false, supportsReasoningEffort: true, defaultTemperature: 0.6, notes: "Reasoning endpoint alias in some SDKs." }),
      m({ modelId: "deepseek-coder", displayName: "DeepSeek Coder", category: "coding", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 64_000, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: true, supportsFrequencyPenalty: true, supportsSeed: false, supportsReasoningEffort: false, defaultTemperature: 0.7, notes: "Coding-oriented model variant." }),
    ],
  },
  {
    id: "moonshot",
    displayName: "Moonshot / Kimi",
    docsUrl: "https://platform.moonshot.ai/docs/intro",
    baseUrl: "https://api.moonshot.ai/v1",
    logoPath: "/providers/moonshot.svg",
    keyPlaceholder: "sk-...",
    supportedSettings: ["temperature", "topP", "maxOutputTokens"],
    lastVerified: "2026-03-28",
    notes: "Moonshot model naming can change rapidly across previews.",
    models: [
      m({ modelId: "kimi-k2", displayName: "Kimi K2", category: "reasoning", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: false, supportsReasoningEffort: true, defaultTemperature: 0.7, notes: "Reasoning-centric generation." }),
      m({ modelId: "kimi-k1.5-long", displayName: "Kimi K1.5 Long", category: "flagship", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: false, supportsReasoningEffort: false, defaultTemperature: 0.7, notes: "Long context variant." }),
      m({ modelId: "kimi-k1.5-short", displayName: "Kimi K1.5 Short", category: "fast", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: false, supportsReasoningEffort: false, defaultTemperature: 0.7, notes: "Lower latency variant." }),
      m({ modelId: "moonshot-v1-128k", displayName: "Moonshot V1 128K", category: "balanced", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 128_000, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: false, supportsReasoningEffort: false, defaultTemperature: 0.7, notes: "Common compatibility model." }),
      m({ modelId: "moonshot-v1-8k", displayName: "Moonshot V1 8K", category: "mini", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 8_000, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: false, supportsReasoningEffort: false, defaultTemperature: 0.7, notes: "Small context, cheaper tier." }),
    ],
  },
  {
    id: "qwen",
    displayName: "Qwen",
    docsUrl: "https://help.aliyun.com/zh/model-studio/getting-started/models",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    logoPath: "/providers/qwen.svg",
    keyPlaceholder: "sk-...",
    supportedSettings: ["temperature", "topP", "topK", "presencePenalty", "maxOutputTokens", "seed"],
    lastVerified: "2026-03-28",
    notes: "DashScope model IDs differ between native and OpenAI-compatible endpoints.",
    models: [
      m({ modelId: "qwen-max", displayName: "Qwen Max", category: "flagship", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: true, supportsPresencePenalty: true, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 0.8, notes: "Top Qwen general model." }),
      m({ modelId: "qwen-plus", displayName: "Qwen Plus", category: "balanced", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: true, supportsPresencePenalty: true, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 0.8, notes: "Balanced capability/cost." }),
      m({ modelId: "qwen-turbo", displayName: "Qwen Turbo", category: "fast", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: true, supportsPresencePenalty: true, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 0.8, notes: "Fast lower-cost tier." }),
      m({ modelId: "qwen3-235b-a22b", displayName: "Qwen3 235B A22B", category: "flagship", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: true, supportsPresencePenalty: true, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: true, defaultTemperature: 0.7, notes: "Large MoE frontier family model." }),
      m({ modelId: "qwen-coder-plus", displayName: "Qwen Coder Plus", category: "coding", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: true, supportsPresencePenalty: true, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 0.6, notes: "Coding-optimized model." }),
    ],
  },
  {
    id: "mistral",
    displayName: "Mistral",
    docsUrl: "https://docs.mistral.ai/getting-started/models/models_overview/",
    baseUrl: "https://api.mistral.ai/v1",
    logoPath: "/providers/mistral.svg",
    keyPlaceholder: "mistral-...",
    supportedSettings: ["temperature", "topP", "maxOutputTokens", "seed"],
    lastVerified: "2026-03-28",
    notes: "Mistral model lineup includes open and managed variants.",
    models: [
      m({ modelId: "mistral-large-latest", displayName: "Mistral Large", category: "flagship", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 128_000, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 0.7, notes: "Highest quality managed model." }),
      m({ modelId: "mistral-medium-latest", displayName: "Mistral Medium", category: "balanced", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 128_000, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 0.7, notes: "Balanced quality and cost." }),
      m({ modelId: "mistral-small-latest", displayName: "Mistral Small", category: "fast", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 32_000, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 0.7, notes: "Fast chat inference." }),
      m({ modelId: "ministral-8b-latest", displayName: "Ministral 8B", category: "mini", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 32_000, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 0.7, notes: "Small/efficient model." }),
      m({ modelId: "codestral-latest", displayName: "Codestral", category: "coding", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 32_000, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 0.2, notes: "Code generation specialized." }),
    ],
  },
];

export const CATALOG_BY_ID = Object.fromEntries(PROVIDER_CATALOG.map((provider) => [provider.id, provider]));
