import type { ProviderCatalogEntry, ProviderModel } from "@/types/providers";

const m = (model: ProviderModel): ProviderModel => model;

export const PROVIDER_CATALOG: ProviderCatalogEntry[] = [
  {
    id: "openai",
    displayName: "OpenAI",
    docsUrl: "https://platform.openai.com/docs/models",
    baseUrl: "https://api.openai.com/v1",
    logoPath: "/providers/openai.svg",
    keyPlaceholder: "sk-...",
    supportedSettings: ["temperature", "topP", "presencePenalty", "frequencyPenalty", "maxOutputTokens", "seed", "reasoningEffort"],
    lastVerified: "2026-03-28",
    notes: "Catalog narrowed to currently verified OpenAI family only.",
    models: [
      m({ modelId: "gpt-5.4", displayName: "GPT-5.4", category: "flagship", inputPricePer1M: 2.5, outputPricePer1M: 15, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: true, supportsFrequencyPenalty: true, supportsSeed: true, supportsReasoningEffort: true, defaultTemperature: 1, notes: "Verified pricing set from provided source check." }),
      m({ modelId: "gpt-5.4-mini", displayName: "GPT-5.4 Mini", category: "balanced", inputPricePer1M: 0.75, outputPricePer1M: 4.5, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: true, supportsFrequencyPenalty: true, supportsSeed: true, supportsReasoningEffort: true, defaultTemperature: 1, notes: "Verified pricing set from provided source check." }),
      m({ modelId: "gpt-5.4-nano", displayName: "GPT-5.4 Nano", category: "nano", inputPricePer1M: 0.2, outputPricePer1M: 1.25, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Verified pricing set from provided source check." }),
      m({ modelId: "gpt-5.4-pro", displayName: "GPT-5.4 Pro", category: "reasoning", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: true, supportsFrequencyPenalty: true, supportsSeed: true, supportsReasoningEffort: true, defaultTemperature: 1, notes: "Pricing not hardcoded in this pass." }),
    ],
  },
  {
    id: "gemini",
    displayName: "Google Gemini",
    docsUrl: "https://ai.google.dev/gemini-api/docs/models",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    logoPath: "/providers/gemini.svg",
    keyPlaceholder: "AIza...",
    supportedSettings: ["temperature", "topP", "topK", "maxOutputTokens", "seed"],
    lastVerified: "2026-03-28",
    notes: "All four Gemini safety categories default to BLOCK_NONE and remain user-configurable.",
    models: [
      m({ modelId: "gemini-3.1-pro-preview", displayName: "Gemini 3.1 Pro Preview", category: "flagship", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: true, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Preview model; avoid long-lived production pinning." }),
      m({ modelId: "gemini-3-flash-preview", displayName: "Gemini 3 Flash Preview", category: "fast", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: true, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Preview fast tier." }),
      m({ modelId: "gemini-3.1-flash-lite-preview", displayName: "Gemini 3.1 Flash-Lite Preview", category: "mini", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: true, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Preview low-cost tier." }),
    ],
  },
  {
    id: "anthropic",
    displayName: "Anthropic",
    docsUrl: "https://docs.anthropic.com/en/docs/about-claude/models",
    baseUrl: "https://api.anthropic.com/v1",
    logoPath: "/providers/anthropic.svg",
    keyPlaceholder: "sk-ant-...",
    supportedSettings: ["temperature", "topP", "topK", "maxOutputTokens"],
    lastVerified: "2026-03-28",
    notes: "Only current 4.x family kept.",
    models: [
      m({ modelId: "claude-opus-4-6", displayName: "Claude Opus 4.6", category: "flagship", inputPricePer1M: 5, outputPricePer1M: 25, currency: "USD", contextWindow: 200_000, supportsTemperature: true, supportsTopP: true, supportsTopK: true, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: false, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Verified pricing set from provided source check." }),
      m({ modelId: "claude-sonnet-4-6", displayName: "Claude Sonnet 4.6", category: "balanced", inputPricePer1M: 3, outputPricePer1M: 15, currency: "USD", contextWindow: 200_000, supportsTemperature: true, supportsTopP: true, supportsTopK: true, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: false, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Verified pricing set from provided source check." }),
      m({ modelId: "claude-haiku-4-5", displayName: "Claude Haiku 4.5", category: "fast", inputPricePer1M: 1, outputPricePer1M: 5, currency: "USD", contextWindow: 200_000, supportsTemperature: true, supportsTopP: true, supportsTopK: true, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: false, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Verified pricing set from provided source check." }),
    ],
  },
  {
    id: "xai",
    displayName: "xAI",
    docsUrl: "https://docs.x.ai/docs/models",
    baseUrl: "https://api.x.ai/v1",
    logoPath: "/providers/xai.svg",
    keyPlaceholder: "xai-...",
    supportedSettings: ["temperature", "topP", "maxOutputTokens", "seed", "reasoningEffort"],
    lastVerified: "2026-03-28",
    notes: "Current Grok 4.x line plus code-fast retained.",
    models: [
      m({ modelId: "grok-4.20-reasoning", displayName: "Grok 4.20 Reasoning", category: "reasoning", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: true, defaultTemperature: 1, notes: "Reasoning-optimized variant." }),
      m({ modelId: "grok-4", displayName: "Grok 4", category: "flagship", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Primary Grok 4 model." }),
      m({ modelId: "grok-4-fast", displayName: "Grok 4 Fast", category: "fast", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Low latency tier." }),
      m({ modelId: "grok-4-fast-reasoning", displayName: "Grok 4 Fast Reasoning", category: "reasoning", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: true, defaultTemperature: 1, notes: "Reasoning + fast variant." }),
      m({ modelId: "grok-code-fast-1", displayName: "Grok Code Fast 1", category: "coding", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 0.4, notes: "Coding-specialized fast model." }),
    ],
  },
  {
    id: "deepseek",
    displayName: "DeepSeek",
    docsUrl: "https://api-docs.deepseek.com/quick_start/pricing",
    baseUrl: "https://api.deepseek.com/v1",
    logoPath: "/providers/deepseek.svg",
    keyPlaceholder: "sk-...",
    supportedSettings: ["temperature", "topP", "frequencyPenalty", "presencePenalty", "maxOutputTokens"],
    lastVerified: "2026-03-28",
    notes: "USD tables can vary by page/version; pricing should be re-verified before hardcoding globally.",
    models: [
      m({ modelId: "deepseek-chat", displayName: "DeepSeek Chat", category: "balanced", inputPricePer1M: 0.28, outputPricePer1M: 0.42, currency: "USD", contextWindow: 128_000, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: true, supportsFrequencyPenalty: true, supportsSeed: false, supportsReasoningEffort: false, defaultTemperature: 1, notes: "Using cache-miss figures from provided excerpt." }),
      m({ modelId: "deepseek-reasoner", displayName: "DeepSeek Reasoner", category: "reasoning", inputPricePer1M: 0.28, outputPricePer1M: 0.42, currency: "USD", contextWindow: 128_000, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: false, supportsReasoningEffort: true, defaultTemperature: 0.6, notes: "Using cache-miss figures from provided excerpt." }),
    ],
  },
  {
    id: "moonshot",
    displayName: "Moonshot / Kimi",
    docsUrl: "https://platform.moonshot.ai/docs/intro",
    baseUrl: "https://api.moonshot.ai/v1",
    logoPath: "/providers/moonshot.svg",
    keyPlaceholder: "sk-...",
    supportedSettings: ["temperature", "topP", "maxOutputTokens", "reasoningEffort"],
    lastVerified: "2026-03-28",
    notes: "Only current Kimi K2.5/K2-thinking line retained.",
    models: [
      m({ modelId: "kimi-k2.5", displayName: "Kimi K2.5", category: "flagship", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: false, supportsReasoningEffort: true, defaultTemperature: 0.7, notes: "Current base Kimi model." }),
      m({ modelId: "kimi-k2-thinking", displayName: "Kimi K2 Thinking", category: "reasoning", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: false, supportsReasoningEffort: true, defaultTemperature: 0.7, notes: "Reasoning-focused variant." }),
      m({ modelId: "kimi-k2-thinking-turbo", displayName: "Kimi K2 Thinking Turbo", category: "reasoning", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: false, supportsReasoningEffort: true, defaultTemperature: 0.7, notes: "Advanced turbo reasoning tier." }),
    ],
  },
  {
    id: "qwen",
    displayName: "Qwen",
    docsUrl: "https://help.aliyun.com/zh/model-studio/getting-started/models",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    logoPath: "/providers/qwen.svg",
    keyPlaceholder: "sk-...",
    supportedSettings: ["temperature", "topP", "topK", "presencePenalty", "maxOutputTokens", "seed"],
    lastVerified: "2026-03-28",
    notes: "Qwen pricing is region/deployment-mode specific; do not treat values as universal.",
    models: [
      m({ modelId: "qwen3-max", displayName: "Qwen3 Max", category: "flagship", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: true, supportsPresencePenalty: true, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: true, defaultTemperature: 0.8, notes: "Current top Qwen3 tier." }),
      m({ modelId: "qwen3.5-plus", displayName: "Qwen3.5 Plus", category: "balanced", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: true, supportsPresencePenalty: true, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: true, defaultTemperature: 0.8, notes: "Current balanced Qwen3.5 tier." }),
      m({ modelId: "qwen3.5-flash", displayName: "Qwen3.5 Flash", category: "fast", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: true, supportsPresencePenalty: true, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 0.8, notes: "Current fast Qwen3.5 tier." }),
    ],
  },
  {
    id: "mistral",
    displayName: "Mistral",
    docsUrl: "https://docs.mistral.ai/getting-started/models/models_overview/",
    baseUrl: "https://api.mistral.ai/v1",
    logoPath: "/providers/mistral.svg",
    keyPlaceholder: "mistral-...",
    supportedSettings: ["temperature", "topP", "maxOutputTokens", "seed"],
    lastVerified: "2026-03-28",
    notes: "Current latest/Devstral/Codestral/Ministral families retained.",
    models: [
      m({ modelId: "mistral-large-latest", displayName: "Mistral Large", category: "flagship", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 128_000, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 0.7, notes: "Latest flagship model." }),
      m({ modelId: "mistral-medium-latest", displayName: "Mistral Medium", category: "balanced", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 128_000, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 0.7, notes: "Latest balanced model." }),
      m({ modelId: "mistral-small-latest", displayName: "Mistral Small", category: "fast", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 32_000, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 0.7, notes: "Latest fast model." }),
      m({ modelId: "devstral-latest", displayName: "Devstral", category: "coding", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: null, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 0.4, notes: "Developer-focused model line." }),
      m({ modelId: "codestral-latest", displayName: "Codestral", category: "coding", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 32_000, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 0.2, notes: "Code generation specialist." }),
      m({ modelId: "ministral-14b-latest", displayName: "Ministral 14B", category: "mini", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 32_000, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 0.7, notes: "Compact model family." }),
      m({ modelId: "ministral-8b-latest", displayName: "Ministral 8B", category: "mini", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 32_000, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 0.7, notes: "Compact model family." }),
      m({ modelId: "ministral-3b-latest", displayName: "Ministral 3B", category: "nano", inputPricePer1M: null, outputPricePer1M: null, currency: "USD", contextWindow: 16_000, supportsTemperature: true, supportsTopP: true, supportsTopK: false, supportsPresencePenalty: false, supportsFrequencyPenalty: false, supportsSeed: true, supportsReasoningEffort: false, defaultTemperature: 0.7, notes: "Smallest latest ministral tier." }),
    ],
  },
];

export const CATALOG_BY_ID = Object.fromEntries(PROVIDER_CATALOG.map((provider) => [provider.id, provider]));
